version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mbit
      MYSQL_DATABASE: Pictures
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
    volumes:
      - shared_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_api
    restart: always
    depends_on:
      - db
    environment:
      # Variables que la API usará para conectarse a MySQL
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: Pictures
      DB_USER: mbit
      DB_PASSWORD: mbit
      # Ruta donde la app puede guardar/leer imágenes (montada en el volumen)
      IMAGES_PATH: /app/data
    volumes:
      - shared_data:/app/data
    ports:
      - "8080:8080"

volumes:
  shared_data:


